export const WEATHER_CODE_MAP: Record<number, string> = {
  0: 'clear',
  1: 'mostly-clear',
  2: 'partly-cloudy',
  3: 'overcast',
  45: 'fog',
  48: 'fog',
  51: 'drizzle',
  53: 'drizzle',
  55: 'drizzle',
  56: 'drizzle',
  57: 'drizzle',
  61: 'rain',
  63: 'rain',
  65: 'rain',
  66: 'rain',
  67: 'rain',
  71: 'snow',
  73: 'snow',
  75: 'snow',
  77: 'snow',
  80: 'rain',
  81: 'rain',
  82: 'rain',
  85: 'snow',
  86: 'snow',
  95: 'storm',
  96: 'storm',
  99: 'storm',
}

export const WEATHER_ICON_MAP: Record<string, string> = {
  'clear-day': 'clear-day.svg',
  'clear-night': 'clear-night.svg',
  'mostly-clear-day': 'mostly-clear-day.svg',
  'mostly-clear-night': 'mostly-clear-night.svg',
  'partly-cloudy-day': 'partly-cloudy-day.svg',
  'partly-cloudy-night': 'partly-cloudy-night.svg',
  cloudy: 'cloudy.svg',
  'overcast-day': 'overcast-day.svg',
  'overcast-night': 'overcast-night.svg',
  overcast: 'overcast.svg',
  'fog-day': 'fog-day.svg',
  'fog-night': 'fog-night.svg',
  fog: 'fog.svg',
  'haze-day': 'haze-day.svg',
  'haze-night': 'haze-night.svg',
  haze: 'haze.svg',
  mist: 'mist.svg',
  drizzle: 'drizzle.svg',
  rain: 'rain.svg',
  snow: 'snow.svg',
  storm: 'thunderstorms.svg',
  'wind-fast': 'wind-fast.svg',
  'wind-medium': 'wind-medium.svg',
  'wind-slow': 'wind-slow.svg',
}

export const WEATHER_LABELS: Record<number, string> = {
  0: 'Clear sky',
  1: 'Mainly clear',
  2: 'Partly cloudy',
  3: 'Overcast',
  45: 'Fog',
  48: 'Depositing rime fog',
  51: 'Light drizzle',
  53: 'Moderate drizzle',
  55: 'Dense drizzle',
  56: 'Light freezing drizzle',
  57: 'Dense freezing drizzle',
  61: 'Slight rain',
  63: 'Moderate rain',
  65: 'Heavy rain',
  66: 'Light freezing rain',
  67: 'Heavy freezing rain',
  71: 'Slight snow fall',
  73: 'Moderate snow fall',
  75: 'Heavy snow fall',
  77: 'Snow grains',
  80: 'Slight rain showers',
  81: 'Moderate rain showers',
  82: 'Violent rain showers',
  85: 'Slight snow showers',
  86: 'Heavy snow showers',
  95: 'Thunderstorm',
  96: 'Thunderstorm with slight hail',
  99: 'Thunderstorm with heavy hail',
}

export function getWeatherIcon(code: number, isDay: boolean): string {
  const state = WEATHER_CODE_MAP[code] ?? 'cloudy'
  const key = isDay ? `${state}-day` : `${state}-night`
  return WEATHER_ICON_MAP[key] ?? WEATHER_ICON_MAP[state] ?? 'cloudy.svg'
}
